### ISSUE TITLE
评论不能

### ISSUE THREAD

**Issue by zmofei** [bh-lay/blog#9]
![image](https://cloud.githubusercontent.com/assets/3351337/8558715/fc4b413c-2538-11e5-806e-9868491895ec.png)

如图，打字的时候看不见我所写的文字，但是可以发出来

**Comment by bh-lay** [comment]
已经搞定，请查验 http://bh-lay.com/bless

**Comment by zmofei** [comment]
ok 好了
但是有新问题了
http://bh-lay.com/bless 
我不喜欢这个地址

**Comment by bh-lay** [comment]
信不信我打你！

**Comment by zmofei** [comment]
艹 ， 关了还能评论
